import { ComponentMetadata } from "@/types/docs";

export const components: ComponentMetadata[] = [
  // Input Components
  {
    name: "button",
    medievalName: "Command Rune",
    category: "input",
    description: "Medieval-styled button with decorative text wrapping and unique clip-path shapes",
    installCommand: "npx medievalui add button",
    dependencies: ["@radix-ui/react-slot"],
    hasDemo: true,
  },
  {
    name: "input",
    medievalName: "Inscription Field",
    category: "input",
    description: "Text input field with medieval border styling",
    installCommand: "npx medievalui add input",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "textarea",
    medievalName: "Scroll Field",
    category: "input",
    description: "Multi-line text input with medieval theming",
    installCommand: "npx medievalui add textarea",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "checkbox",
    medievalName: "Mark of Choice",
    category: "input",
    description: "Checkbox with medieval styling and animations",
    installCommand: "npx medievalui add checkbox",
    dependencies: ["@radix-ui/react-checkbox"],
    hasDemo: true,
  },
  {
    name: "radio-group",
    medievalName: "Circle of Selection",
    category: "input",
    description: "Radio button group with medieval theming",
    installCommand: "npx medievalui add radio-group",
    dependencies: ["@radix-ui/react-radio-group"],
    hasDemo: true,
  },
  {
    name: "switch",
    medievalName: "Toggle Lever",
    category: "input",
    description: "Toggle switch with smooth animations",
    installCommand: "npx medievalui add switch",
    dependencies: ["@radix-ui/react-switch"],
    hasDemo: true,
  },
  {
    name: "slider",
    medievalName: "Value Scribe",
    category: "input",
    description: "Range slider with medieval styling",
    installCommand: "npx medievalui add slider",
    dependencies: ["@radix-ui/react-slider"],
    hasDemo: true,
  },
  {
    name: "select",
    medievalName: "Scroll of Options",
    category: "input",
    description: "Dropdown select with medieval theming",
    installCommand: "npx medievalui add select",
    dependencies: ["@radix-ui/react-select"],
    hasDemo: true,
  },
  {
    name: "label",
    medievalName: "Inscription Mark",
    category: "input",
    description: "Form label with medieval typography",
    installCommand: "npx medievalui add label",
    dependencies: ["@radix-ui/react-label"],
    hasDemo: true,
  },
  {
    name: "input-otp",
    medievalName: "Rune Sequence",
    category: "input",
    description: "One-time password input with individual character cells",
    installCommand: "npx medievalui add input-otp",
    dependencies: ["input-otp"],
    hasDemo: true,
  },
  {
    name: "input-group",
    medievalName: "Inscription Group",
    category: "input",
    description: "Grouped input fields with addons",
    installCommand: "npx medievalui add input-group",
    dependencies: [],
    hasDemo: true,
  },

  // Display Components
  {
    name: "card",
    medievalName: "Parchment",
    category: "display",
    description: "Content container with medieval borders and styling",
    installCommand: "npx medievalui add card",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "badge",
    medievalName: "Seal",
    category: "display",
    description: "Small label with decorative dots and medieval styling",
    installCommand: "npx medievalui add badge",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "avatar",
    medievalName: "Portrait",
    category: "display",
    description: "User avatar with fallback and medieval frame",
    installCommand: "npx medievalui add avatar",
    dependencies: ["@radix-ui/react-avatar"],
    hasDemo: true,
  },
  {
    name: "alert",
    medievalName: "Herald's Call",
    category: "display",
    description: "Alert message with medieval styling and icons",
    installCommand: "npx medievalui add alert",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "separator",
    medievalName: "Dividing Line",
    category: "display",
    description: "Visual separator with medieval styling",
    installCommand: "npx medievalui add separator",
    dependencies: ["@radix-ui/react-separator"],
    hasDemo: true,
  },
  {
    name: "skeleton",
    medievalName: "Loading Shade",
    category: "display",
    description: "Loading placeholder with pulsing animation",
    installCommand: "npx medievalui add skeleton",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "spinner",
    medievalName: "Spinning Wheel",
    category: "display",
    description: "Loading spinner with medieval theming",
    installCommand: "npx medievalui add spinner",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "progress",
    medievalName: "Journey Bar",
    category: "display",
    description: "Progress indicator with medieval styling",
    installCommand: "npx medievalui add progress",
    dependencies: ["@radix-ui/react-progress"],
    hasDemo: true,
  },
  {
    name: "empty",
    medievalName: "Void State",
    category: "display",
    description: "Empty state placeholder with medieval imagery",
    installCommand: "npx medievalui add empty",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "kbd",
    medievalName: "Key Rune",
    category: "display",
    description: "Keyboard key display with medieval styling",
    installCommand: "npx medievalui add kbd",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "item",
    medievalName: "List Fragment",
    category: "display",
    description: "List item component with medieval theming",
    installCommand: "npx medievalui add item",
    dependencies: [],
    hasDemo: true,
  },

  // Navigation Components
  {
    name: "navigation-menu",
    medievalName: "Wayfinder",
    category: "navigation",
    description: "Complex navigation menu with medieval styling",
    installCommand: "npx medievalui add navigation-menu",
    dependencies: ["@radix-ui/react-navigation-menu"],
    hasDemo: true,
  },
  {
    name: "breadcrumb",
    medievalName: "Path Markers",
    category: "navigation",
    description: "Breadcrumb navigation with medieval separators",
    installCommand: "npx medievalui add breadcrumb",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "pagination",
    medievalName: "Page Turner",
    category: "navigation",
    description: "Pagination controls with medieval styling",
    installCommand: "npx medievalui add pagination",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "tabs",
    medievalName: "Tabbed Scrolls",
    category: "navigation",
    description: "Tabbed interface with medieval theming",
    installCommand: "npx medievalui add tabs",
    dependencies: ["@radix-ui/react-tabs"],
    hasDemo: true,
  },
  {
    name: "menubar",
    medievalName: "Command Bar",
    category: "navigation",
    description: "Menu bar with medieval styling",
    installCommand: "npx medievalui add menubar",
    dependencies: ["@radix-ui/react-menubar"],
    hasDemo: true,
  },

  // Overlay Components
  {
    name: "dialog",
    medievalName: "Modal Chamber",
    category: "overlay",
    description: "Modal dialog with medieval frame and backdrop",
    installCommand: "npx medievalui add dialog",
    dependencies: ["@radix-ui/react-dialog"],
    hasDemo: true,
  },
  {
    name: "alert-dialog",
    medievalName: "Warning Chamber",
    category: "overlay",
    description: "Alert dialog for confirmations with medieval styling",
    installCommand: "npx medievalui add alert-dialog",
    dependencies: ["@radix-ui/react-alert-dialog"],
    hasDemo: true,
  },
  {
    name: "drawer",
    medievalName: "Side Chamber",
    category: "overlay",
    description: "Slide-out drawer with medieval theming",
    installCommand: "npx medievalui add drawer",
    dependencies: ["vaul"],
    hasDemo: true,
  },
  {
    name: "sheet",
    medievalName: "Sliding Scroll",
    category: "overlay",
    description: "Side sheet overlay with medieval styling",
    installCommand: "npx medievalui add sheet",
    dependencies: ["@radix-ui/react-dialog"],
    hasDemo: true,
  },
  {
    name: "popover",
    medievalName: "Floating Parchment",
    category: "overlay",
    description: "Popover with medieval frame and positioning",
    installCommand: "npx medievalui add popover",
    dependencies: ["@radix-ui/react-popover"],
    hasDemo: true,
  },
  {
    name: "tooltip",
    medievalName: "Whisper Text",
    category: "overlay",
    description: "Tooltip with medieval styling and animations",
    installCommand: "npx medievalui add tooltip",
    dependencies: ["@radix-ui/react-tooltip"],
    hasDemo: true,
  },
  {
    name: "hover-card",
    medievalName: "Reveal Parchment",
    category: "overlay",
    description: "Hover card with medieval theming",
    installCommand: "npx medievalui add hover-card",
    dependencies: ["@radix-ui/react-hover-card"],
    hasDemo: true,
  },
  {
    name: "dropdown-menu",
    medievalName: "Cascade Scroll",
    category: "overlay",
    description: "Dropdown menu with medieval styling",
    installCommand: "npx medievalui add dropdown-menu",
    dependencies: ["@radix-ui/react-dropdown-menu"],
    hasDemo: true,
  },
  {
    name: "context-menu",
    medievalName: "Right-Click Scroll",
    category: "overlay",
    description: "Context menu with medieval theming",
    installCommand: "npx medievalui add context-menu",
    dependencies: ["@radix-ui/react-context-menu"],
    hasDemo: true,
  },
  {
    name: "command",
    medievalName: "Command Palette",
    category: "overlay",
    description: "Command palette with medieval styling",
    installCommand: "npx medievalui add command",
    dependencies: ["cmdk"],
    hasDemo: true,
  },

  // Form Components
  {
    name: "form",
    medievalName: "Inscription Form",
    category: "form",
    description: "Form component with validation and medieval styling",
    installCommand: "npx medievalui add form",
    dependencies: ["@radix-ui/react-label", "@radix-ui/react-slot", "react-hook-form"],
    hasDemo: true,
  },
  {
    name: "field",
    medievalName: "Form Field",
    category: "form",
    description: "Form field wrapper with medieval theming",
    installCommand: "npx medievalui add field",
    dependencies: [],
    hasDemo: true,
  },

  // Layout Components
  {
    name: "sidebar",
    medievalName: "Side Panel",
    category: "layout",
    description: "Collapsible sidebar with medieval styling",
    installCommand: "npx medievalui add sidebar",
    dependencies: ["@radix-ui/react-separator"],
    hasDemo: true,
  },
  {
    name: "scroll-area",
    medievalName: "Scroll Chamber",
    category: "layout",
    description: "Custom scrollable area with medieval scrollbars",
    installCommand: "npx medievalui add scroll-area",
    dependencies: ["@radix-ui/react-scroll-area"],
    hasDemo: true,
  },
  {
    name: "resizable",
    medievalName: "Adjustable Panels",
    category: "layout",
    description: "Resizable panel layout with medieval handles",
    installCommand: "npx medievalui add resizable",
    dependencies: ["react-resizable-panels"],
    hasDemo: true,
  },
  {
    name: "aspect-ratio",
    medievalName: "Frame Ratio",
    category: "layout",
    description: "Aspect ratio container for medieval frames",
    installCommand: "npx medievalui add aspect-ratio",
    dependencies: ["@radix-ui/react-aspect-ratio"],
    hasDemo: true,
  },

  // Data Components
  {
    name: "table",
    medievalName: "Data Ledger",
    category: "data",
    description: "Data table with medieval borders and styling",
    installCommand: "npx medievalui add table",
    dependencies: [],
    hasDemo: true,
  },
  {
    name: "chart",
    medievalName: "Visual Chronicle",
    category: "data",
    description: "Charts and graphs with medieval theming",
    installCommand: "npx medievalui add chart",
    dependencies: ["recharts"],
    hasDemo: true,
  },
  {
    name: "calendar",
    medievalName: "Time Keeper",
    category: "data",
    description: "Date picker calendar with medieval styling",
    installCommand: "npx medievalui add calendar",
    dependencies: ["react-day-picker"],
    hasDemo: true,
  },

  // Interactive Components
  {
    name: "accordion",
    medievalName: "Expandable Scroll",
    category: "display",
    description: "Collapsible sections with medieval theming",
    installCommand: "npx medievalui add accordion",
    dependencies: ["@radix-ui/react-accordion"],
    hasDemo: true,
  },
  {
    name: "collapsible",
    medievalName: "Fold Panel",
    category: "display",
    description: "Collapsible content with medieval styling",
    installCommand: "npx medievalui add collapsible",
    dependencies: ["@radix-ui/react-collapsible"],
    hasDemo: true,
  },
  {
    name: "carousel",
    medievalName: "Sliding Gallery",
    category: "display",
    description: "Image carousel with medieval navigation",
    installCommand: "npx medievalui add carousel",
    dependencies: ["embla-carousel-react"],
    hasDemo: true,
  },
  {
    name: "toggle",
    medievalName: "Switch Rune",
    category: "input",
    description: "Toggle button with medieval styling",
    installCommand: "npx medievalui add toggle",
    dependencies: ["@radix-ui/react-toggle"],
    hasDemo: true,
  },
  {
    name: "toggle-group",
    medievalName: "Rune Group",
    category: "input",
    description: "Group of toggle buttons with medieval theming",
    installCommand: "npx medievalui add toggle-group",
    dependencies: ["@radix-ui/react-toggle-group"],
    hasDemo: true,
  },
  {
    name: "button-group",
    medievalName: "Command Group",
    category: "input",
    description: "Group of buttons with medieval styling",
    installCommand: "npx medievalui add button-group",
    dependencies: [],
    hasDemo: true,
  },

  // Feedback Components
  {
    name: "sonner",
    medievalName: "Toast Herald",
    category: "feedback",
    description: "Toast notifications with medieval theming",
    installCommand: "npx medievalui add sonner",
    dependencies: ["next-themes", "sonner"],
    hasDemo: true,
  },

  // Special Components
  {
    name: "background-lines",
    medievalName: "Pattern Weave",
    category: "display",
    description: "Animated background lines with medieval patterns",
    installCommand: "npx medievalui add background-lines",
    dependencies: ["motion"],
    hasDemo: true,
  },
];

export const componentsByCategory = components.reduce((acc, component) => {
  if (!acc[component.category]) {
    acc[component.category] = [];
  }
  acc[component.category].push(component);
  return acc;
}, {} as Record<string, ComponentMetadata[]>);
